#!/bin/zsh

trap exit_gen INT EXIT

function exit_gen() {
    echo "Kill wxscrab_gen: $PID"
    kill ${PID}
}

# serveur de partie/dico
cd ~/wxscrab_gen/server
./server.py &
PID=$!
echo "Gen pid:" $PID

cd ~/wxscrab/server
./go.py -p1991  -o   -c90  -i10  --minpoint 900 --mintour 18  --maxtour 22
